---
- hosts: proxies
  tasks:
    - file: path=/var/log/haproxy.log state=touch mode="u=rw,g=r,o=r"
    - name: ensure that rsyslog is configured to log local2 to haproxy.log
      lineinfile:
        dest: /etc/rsyslog.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        insertafter: "{{ item.after }}"
      with_items:
        - { regexp: '^local2', line: 'local2.*              /var/log/haproxy.log', after: '^local7' }
        - { regexp: '^#$ModLoad imudp', line: '$ModLoad imudp', after: EOF }
        - { regexp: '^#$UDPServerRun 514', line: '$UDPServerRun 514', after: EOF }
        - { regexp: '^$UDPServerAddress', line: '$UDPServerAddress 127.0.0.1', after: '^$UDPServerRun' }
      notify:
      - restart rsyslog
    - name: Make certain latest version of Apache is installed
      yum: name=haproxy state=latest
    - lineinfile: dest=/etc/haproxy/haproxy.cfg regexp=^frontend line="frontend  main *:80"
    - lineinfile: dest=/etc/haproxy/haproxy.cfg regexp=^(\s+)stats(\s)socket(.*) line="    stats socket /var/run/haproxy.sock"
    - replace: dest=/etc/haproxy/haproxy.cfg regexp='(\s+)server(\s+)app[0-9](\s+.*)' backup=yes
    - name: insert backend webservers
      blockinfile:
        dest: /etc/haproxy/haproxy.cfg
        content: |
          {% for host in groups['webservers'] %}
              server {{ host.split('.')[0] }} {{ host }}:80 check
          {% endfor %}
    - service: name=haproxy state=restarted enabled=yes
    - firewalld: service=http permanent=true state=enabled immediate=true
  handlers:
    - name: restart rsyslog
      service: name=rsyslog state=restarted
