---
- hosts: localhost
  vars:
    zonename: "example.com"
  tasks:
    - name: make certain bind is installed on this host and is serving to clients
      yum: name=bind state=latest
    - name: ensure that named is correctly configured
      lineinfile:
        dest: /etc/named.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '[\s]listen-on[\s]', line: "\tlisten-on port 53 { any; };" }
        - { regexp: '[\s]allow-query[\s]', line: "\tallow-query      { any; };" }
        - { regexp: '[\s]forwarders[\s][\s\S]*}\;', line: "\tforwarders { 8.8.8.8; 8.8.4.4; };" }
      notify:
      - restart named
    - name: Ensure ZoneName domain is present
      blockinfile:
        dest: /etc/named.conf
        content: |
          zone "{{zonename}}" IN {
            type master;
            file "data/{{zonename}}";
          };
      notify:
      - restart named
    - file: path=/var/named/data/{{zonename}} state=touch owner=named group=named mode="u=rw,g=r,o=r"
    - name: ensure that the ZoneName zone file is correctly configured
      lineinfile:
        dest: /var/named/data/{{zonename}}
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^@', line: "@ in soa localhost. root 1 3H 15M 1W 1D" }
        - { regexp: '[\s]ns[\s]', line: "  ns localhost." }
      notify:
      - restart named
    - name: ensure that firewalld allows for DNS lookups against this server
      firewalld: service=dns permanent=true state=enabled
  handlers:
    - name: restart named
      service: name=named state=restarted
  
