---
- hosts: Location-B
  tasks:
    - hostname: name={{ inventory_hostname }}
      tags:
      - configuration
    - redhat_subscription: state=absent
      tags:
      - subscription
    - shell: /usr/sbin/subscription-manager clean
      tags:
      - subscription
    - redhat_subscription: state=present
        activationkey=Employee_SKU_virt
        org_id=7847483
        pool='^Red Hat Enterprise Server$'
        autosubscribe=yes
      tags:
      - subscription
    - shell: /usr/sbin/subscription-manager repos --disable=*
      tags:
      - subscription
    - shell: /usr/sbin/subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-server-rhscl-7-rpms 
      tags:
      - subscription
    - shell: echo "======= Standard MOTD file =======" > /etc/motd
      tags:
      - configuration
    - name: "Install Common RPMS"
      yum: state=present name={{ item }}
      with_items:
      - bash-completion
      - tcpdump
      - vim
      - nmap-ncat
      - bind-utils
      - chrony
      - NetworkManager-glib
      - nm-connection-editor
      - libsemanage-python
      - policycoreutils-python
      tags:
      - packages
    - service: name=chronyd state=started enabled=yes
      tags:
      - services
