---
- hosts: Location-B
  tasks:
    - name: Get a list of containers from the file in the host
      shell: cat /root/list_of_containers.txt
      register: contlist
      
    - name: Create containers and start httpd
      shell: docker run --rm --name {{ item.split(',')[0] }} -v /root/{{ item.split(',')[0] }}:/var/www/html -p {{ item.split(',')[1] }}:80 rhel-apache /usr/sbin/apache2ctl -D FOREGROUND
      with_items: contlist.stdout
