---
- hosts: Location-B
  tasks:
    - name: Get a list of containers from the file in the host
      shell: cat /root/list_of_containers.txt
      register: contlist
      
    - name: Echo the name of the containers in the list
      shell: docker run --name {{ item.split(',')[0] }} rhel-apache "echo {{ item.split(',')[0] }} > /var/www/html/index.html"
      with_items: contlist.stdout_lines
      
    - name: Commit the rhel_httpd container to a docker image
      shell: docker commit {{ item.split(',')[0] }} {{ item.split(',')[0] }}
      with_items: contlist.stdout_lines
      
    - name: Remove the rhel_httpd container that was used to create the image
      docker_container:
        name: {{ item.split(',')[0] }}
        state: absent
      with_items: contlist.stdout_lines
