---
- hosts: Location-B
  tasks:
    - name: Get a list of containers from the file in the host
      shell: cat /root/list_of_containers.txt
      register: contlist
      
    - name: Echo the name of the containers in the list
      shell: touch /tmp/{{ item.split(',')[0] }}
      with_items: contlist.stdout_lines
