---
- hosts: all
  tasks:
    - name: Get a list of containers from the file in the host
      shell: cat /var/list_of_containers.txt
      register: contlist
      
    - name: Create or restart containers
      docker_container:
        name: "{{ item.split(',')[0] }}"
        volumes: "/var/apache/{{ item.split(',')[0] }}/:/var/www/html/"
        ports: 0.0.0.0:{{ item.split(',')[1] }}:80
        exposed_ports: 80
        image: rhel-apache
        command: /usr/sbin/apachectl -D FOREGROUND
        state: started
      with_items: contlist.stdout_lines
      ignore_errors: True
      
    - name: Create /var/apache subdirs for each container
      file: path=/var/apache/{{ item.split(',')[0] }} state=directory mode=0755
      with_items: contlist.stdout_lines
        
    - name: Create index.html files in /var/apache for each container
      shell: echo "Welcome to server {{ item.split(',')[0] }}" > /var/apache/{{ item.split(',')[0] }}/index.html
      with_items: contlist.stdout_lines
      
    - name: Ensure that the SELinux context is set correctly on the container bind mounts
      shell: /usr/bin/chcon -Rt svirt_sandbox_file_t /var/apache/
