---
- hosts: Location-B
  tasks:
    - name: Get a list of containers from the file in the host
      shell: cat /root/list_of_containers.txt
      register: contlist
      
    - name: echo out what we read from the file
      shell: echo {{ item }}
      with_items: contlist.stdout_lines
