---
- hosts: Location-B
  tasks:
    - name: Get a list of containers from the file in the host
      shell: cat /root/list_of_containers.txt
      register: contlist
      
#    - name: Create containers and start httpd in each of them
#      shell: docker run -d --name {{ item.split(',')[0] }} -v /var/apache/{{ item.split(',')[0] }}/:/var/www/html/ -p {{ item.split(',')[1] }}:80 rhel-apache /usr/sbin/apachectl -D FOREGROUND
#      with_items: contlist.stdout_lines
#      ignore_errors: True

#    - name: Start containers that could not be created new
#      shell: docker start -d --name {{ item.split(',')[0] }}
#      with_items: contlist.stdout_lines
#      ignore_errors: True

#    - name: Ensure that containers exist and are running httpd
#      docker_container:
#        name: "{{ item.split(',')[0] }}"
#        devices: "/var/apache/{{ item.split(',')[0] }}/:/var/www/html/:rwm"
#        published_ports: "{{ item.split(',')[1] }}:80"
#        image: rhel-apache
#        command: /usr/sbin/apachectl -D FOREGROUND
#        state: present
#      with_items: contlist.stdout_lines
#      ignore_errors: True
      
    - name: test
      docker_container:
        name: "vCPE-container22"
        volumes: "/var/apache/vCPE-container22/:/var/www/html/"
        ports: "0.0.0.0:9022:80"
        exposed_ports: "9022:80"
        image: rhel-apache
        command: /usr/sbin/apachectl,-D,FOREGROUND
        state: started
      with_items: contlist.stdout_lines
      ignore_errors: True
      
    - name: Create containers and start httpd in each of them
      shell: docker run -d --name vCPE-container23 -v /var/apache/vCPE-container23/:/var/www/html/ -p 9023:80 rhel-apache /usr/sbin/apachectl -D FOREGROUND
      ignore_errors: True

    - name: Create /var/apache subdirs for each container
      file: path=/var/apache/{{ item.split(',')[0] }} state=directory mode=0755
      with_items: contlist.stdout_lines
        
    - name: Create index.html files in /var/apache for each container
      shell: echo "Welcome to server {{ item.split(',')[0] }}" > /var/apache/{{ item.split(',')[0] }}/index.html
      with_items: contlist.stdout_lines
      
    - name: Ensure that the SELinux context is set correctly on the container bind mounts
      shell: /usr/bin/chcon -Rt svirt_sandbox_file_t /var/apache/
