---
- hosts: all
  tasks:
    - name: Test for docker listening on port 2376
      shell: grep "0.0.0.0:2376" /etc/sysconfig/docker-network
      ignore_errors: yes
      register: port_listening
      
    - name: Docker must listen on TCP port 2376
      lineinfile: dest=/etc/sysconfig/docker-network regexp=^DOCKER_NETWORK_OPTIONS= line=DOCKER_NETWORK_OPTIONS="-H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock"
      when: port_listening|failed
      notify:
      - restart docker
      
  handlers:
    - name: restart docker
      service: name=docker state=restarted

